# -*- coding: utf-8 -*-
"""Lecture13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13OTREwoOwxiRbDji8S8H4Qt7YwsdVziP
"""

def show(name,age):
  print("kida", name)
  print("age is ", age)

show("kaushal", 23)

# default argument

def hi(name = "Manoj"):
  print(name)

hi()

def check(num):
  if num % 2 == 0:
    return "Even"
  else:
        return "odd"

print(check(15))

def greet(name):
  print("Hello", name)

greet("krishna")

def total(numbers):
  s = 0

  for n in numbers:
    s += n

  return s

print(total([5, 10, 15]))

def total(numbers):
  s = 1

  for n in numbers:
    s += n

  return s

print(total([5, 10, 15]))

def display():
  return "CGC"

print(display())

def largest(a, b):
  if a > b:
    return a
  else:
      return b

print(largest(5, 10))

"""### ***Dictionary***"""

student = ["Rahul", 22, 91.5, "Nagpur"]

student

student = { "name": "Rahul",
           "age" :22,
           "CGPA" :91.5,
           "city" :"Nagpur"}

student

type(student)

print(student["name"])
print(student["age"])
print(student["CGPA"])
print(student["city"])

student["age"] = 23

student

student["state"] = "Maharashta"

student

student.get("age")

student.get("address", "key is not found")

student.get("age", "key is not found")

student.pop("state")

student

"""## Loop in Dictionaries"""

student

for k in student.keys():
  print(k)

for elem in student.values():
  print(elem)

for element in student.items():
  print(element)

for element in student.items():
  print("key = ", element[0],  ",value = ", element[1])

stdent = {
    "name" : "koko",
    "age" : 76
}

print(stdent["name"])

st = {
    "name" : "rahul"
}

st["age"] = 77

print(st)

stdent = {
    "name" : "koko",
    "age" : 76
}

print(len(stdent))

stdent = {
    "name" : "koko",
    "age" : 76
}

print(stdent.get("city"))

stdent

print(stdent["city"])

print(stdent.keys())

print(stdent.values())

for key in stdent.keys():
  print(student[key])

naam = {
    "name" :"kiyansh",
    "city": "Pathankot"
}

naam.pop("city")

print(naam)

marks =  {
    "math" : 90,
    "science" : 85,
    "english" : 95
}

total = 0

for subject in marks:
  total += marks[subject]

print(total)

marks =  {
    "math" : 90,
    "science" : 85,
    "english" : 95
}

total = 0

for subject in marks.values():
  total += subject

print(total)

cart = {
    "milk":2,
    "bread" : 1
}
cart["Eggs"] = 12
print(len(cart))

employee = {
    "salary" : 50000
}
employee["salary"] += 10000
print(employee["salary"])

scholar = {
     "name" : "nitasha",
     "age": 22
}
count =0
for key in scholar.keys():
  count += 1

print(count)

scholar["city"] = "jalandhar"
scholar["age"] += 1

print(scholar["age"])

Marks =  {
    "math" : 90,
    "science" : 80,
    "english" : 70
}

total =0

for subject in Marks:
  total += Marks[subject]


print((total / len(Marks)))

employee = {
    "salary" : 50000
}
employee["salary"]  = employee["salary"] * 1.10
print(employee["salary"])

data = {
    "A" : 10,
    "B" : 20,
    "C" : 30
}
count =0
for key in data:
  if data[key] > 15:
    count += 1

print(count)

scholar = {
     "name" : "nitasha",
     "age": 22,
     "city" : "ambala"
}
for key in scholar.keys():
  print(len(key))

