select  p.ProductName,sum(o.Total) as T_sales
from `e1.products` as p
inner join `e1.order_items` as o
on p.ProductID = o.ProductID
group by p.ProductName


select 
c.CategoryID,
c.CategoryName, sum(o.Total) as T_SALES
from `e1.products` as p
inner join `e1.order_items` as o
on p.ProductID = o.ProductID
inner join `e1.categories` as c
on c.CategoryID = p.CategoryID
group by  c.CategoryID ,c.CategoryName
order by T_SALES desc



-- Calculate total sales generated by products ferom esach supplier

select  
 s.SupplierID,
 s.SupplierName, 
 sum(o.Total) as T_Sales
from `e1.products` as p
inner join `e1.order_items` as o
on p.ProductID = o.ProductID
inner join `e1.suppliers` as s
on p.SupplierID = s.SupplierID
group by  s.SupplierID,
 s.SupplierName
  order by T_Sales desc
























