-- for every order -item record, display:

-- ProductID
-- SelingPrice
-- Average selling price of that product



-- select
-- ProductID,
-- SellingPrice,
-- avg(SellingPrice) over(partition by ProductID) as avg_prd_sp
-- from `e1.order_items`

-- Display every order-item record and assign a row number based on Total, from highest to lowest


-- select 
-- ProductID,
-- total,
-- row_number() over(order by total desc) as sales_rank
-- from `e1.order_items`



-- for every product, assign a row number to its order-item records
-- based on sales from high to low.



-- select 
-- ProductID,
-- OrderID,
-- Total,
-- row_number() over(partition by ProductID order by Total desc) 
-- from `e1.order_items`



-----CTE----> Common Table Expression

-- with product_sales as (
--   select
--    ProductID,
--   sum(Total) as total_sales
--   from `e1.order_items`
--   group by ProductID
-- )

-- select 
-- ProductID,
-- total_sales,

-- rank() over(order by total_sales desc) as sales_rank
-- from product_sales




-- rank()
-- p1 -> 1
-- p2 -> 2
-- p3 -> 2
-- p4 -> 4


-- dense_rank()
-- p1 -> 1
-- p2 -> 2
-- p3 -> 2
-- p4 -> 3





-- for every customer , show the number of orders they have placed, including customers with zero orders







-- select 
-- c.CustomerID,
-- c.Name,
-- count(o.OrderID) as order_count
-- from `e1.orders` as o
-- inner join `e1.customers` as c 
-- on o.CustomerID = c.CustomerID
-- group by c.CustomerID,
-- c.Name
-- order by order_count desc





-- show every order with;
-- customername
-- Product name
-- category 
-- quantity
-- selling price
-- tottal


-- select
-- c.Name,
-- p.ProductName,
-- ca.CategoryID,
-- ca.CategoryName,
-- oi.Quantity,
-- oi.SellingPrice,
-- oi.Total
-- from `e1.customers` as c    
-- inner join `e1.orders` as o   
-- on c.CustomerID = o.CustomerID
-- inner join `e1.order_items` as oi   
-- on oi.OrderID = o.OrderID
-- INNER JOIN `e1.products` AS p     
-- on  oi.ProductID = p.ProductID
-- inner join `e1.categories` as ca    
-- on  p.CategoryID =  ca.CategoryID



-- customername
-- productname
-- category
-- quantity
-- sellingprice
-- total

-- sles by caeegory and supplier



-- select 
-- c.CategoryName,
-- s.SupplierName,
-- sum(oi.Total)  as total_sales
-- from `e1.categories` as c    
-- inner  join `e1.products` as  p  
-- on c.CategoryID  = p.CategoryID
-- inner join `e1.suppliers` as   s  
-- on s.SupplierID = p.SupplierID
-- inner join `e1.order_items` as oi
-- on p.ProductID = oi.ProductID
-- group by c.CategoryName,
-- s.SupplierName
-- order by total_sales desc



-- how many different products has each customer purchased?


-- select
-- c.CustomerID,
-- count( distinct oi.ProductID) as diff
-- from `e1.customers` as c    
-- inner join `e1.orders` as o   
-- on o.CustomerID = c.CustomerID
-- inner join `e1.order_items` as oi   
-- on o.OrderID  = oi.OrderID
-- group by c.CustomerID
-- order by diff desc





-- the management wants to understand which productscategories are generating the most revenue

-- Using the products , categories , and order_items tables, callluate the total sales genertaed by each category

-- display:
-- categoryID
-- catgoryNmae
-- total sales
-- number of diferent products sold

-- Only include categories eheerere the total sales are greater than 1 00 000
-- Sort the result from highest to lowest total sales.




-- select
-- c.CategoryID,
-- c.CategoryName, sum(oi.Total) as total_sales
-- from `e1.categories` as c    
-- join `e1.products` as    p   
-- on c.CategoryID = p.CategoryID
-- join `e1.order_items` as oi   
-- on oi.ProductID = p.ProductID
-- group by c.CategoryID,
-- c.CategoryName
-- having total_sales > 100000
-- order  by total_sales desc











-- The marketing team wants a identify  customers who have generated significant revernue.

-- Using the customers, orders, and order_items tables, calculate the total amount spent by each customer


-- Display:

-- CustomerID
-- Customer Nma e
-- city
-- total spent 

-- Only dispay customer s whose total spending  is greater than 50 000
-- sort customer sfrom highest spender to lowert spender.


-- select 
-- c.CustomerID,
-- c.name,
-- c.City,
-- sum(oi.Total) as t_s
-- from `e1.customers`as c  
-- inner join `e1.orders` as o 
-- on c.CustomerID = o.CustomerID
-- inner join  `e1.order_items` as oi   
-- on o.OrderID = oi.OrderID
-- group by 
-- c.CustomerID,
-- c.name,
-- c.City
-- having t_s > 50000
-- order by t_s desc


-- the procurrement team wants to compare suppliers based on tht sales generted by tthe products they spply.

-- Using supplier s products, and orders_items , calculate:
-- Suplierid,
-- supplier name
-- number of products supplied
-- total sals generated by those products

-- display only suppliers whose products have generated more than 200 000
-- sort by tootal sales in ascending  order.




select 
s.SupplierID,
s.SupplierName,
count(distinct p.ProductID) as product_supplied, 
sum(oi.total) as total_sales
from `e1.suppliers` as s   
inner join `e1.products` as   p
on s.SupplierID = p.SupplierID
inner join `e1.order_items` as oi
on p.ProductID  = oi.ProductID
group by s.SupplierID, s.SupplierName
having total_sales >  200000
order by total_sales desc









